


#RF Bridge Commands and rules:
backlog switchretain on; powerretain on
#this is the topic you will find your rf device code XXXXXX is the unique code for that device
tele/RF_Bridge/RESULT = {"RfReceived":{"Sync":5160,"Low":390,"High":800,"Data":"XXXXXX","RfKey":"None"}}

# replace XXXXXX with the data code received from the RF bridge from your RF sensor
# you can change the topics to what ever you want (mbdoor/data) for example
rule1 on RfReceived#Data=XXXXXX do publish2 mbdoor/data OPEN endon on RfReceived#Data=XXXXXX do publish2 mbdoor/data CLOSED endon on RfReceived#Data=XXXXXX do publish2 boysdoor/data OPEN endon on RfReceived#Data=XXXXXX do publish2 boysdoor/data CLOSED endon
rule1 1

# here is the rule format
rule1 on <some trigger> do <something> endon on <some trigger> do <something> endon


binary_sensor: #Put this in binary_sensor.yaml

  - platform: mqtt
    name: "Master Bedroom Door"
    state_topic: "mbdoor/data"
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: Door
    optimistic: false
    qos: 1
    retain: false

  - platform: mqtt
    name: "Boys Bedroom Door"
    state_topic: "boysdoor/data"
    payload_on: "OPEN"
    payload_off: "CLOSED"
    device_class: Door
    optimistic: false
    qos: 1
    retain: false
    
automations:   #put this in automations.yaml
#the master bedroom door does not make a sound when the door opens. The automations are for turning on a fan or sound machine in the various rooms are done in Node_Red
  - alias: door boys
    trigger:
      - entity_id: binary_sensor.boys_bedroom_door
        from: 'off'
        platform: state
        to: 'on'
    action:
    - service: media_player.sonos_snapshot
    - service: media_player.volume_set
      data:
        entity_id:
          - media_player.living_room
        volume_level: 0.5
    - service: media_player.play_media
      entity_id:
         - media_player.living_room
#         - media_player.office_speaker_2
         - media_player.master_bedroom_speaker
      data:
        media_content_id: http://xxx.xxx.x.xxx:8123/local/ringingbells.mp3  
        #IP address of HA and file located in www folder
        media_content_type: music
    - delay: 00:00:02
    - service: media_player.sonos_restore